### ISSUE TITLE
[Registro de Usuario] | US-005 | TC-004 | Mensaje en inglés al ingresar un correo ya registrado: "The email x@gmail.com already exists" (ACTUALIZADO)

### ISSUE THREAD

**Issue by marianaluduena** [IgrowkerTraining/i004-wander-back-java#104]
**Descripción del bug:**

**Al intentar registrarse un usuario usando un correo que ya fue previamente registrado, el sistema arroja un mensaje en inglés que dice "The email x@gmail.com already exists"**.

[BUG-002 (Actualizado).xlsx](https://github.com/user-attachments/files/18030023/BUG-002.Actualizado.xlsx)

**Comentarios:**

**- El mensaje obtenido debería mostrarse en español para no afectar la experiencia del usuario y no generarle desconfianza al estar navegando en un sitio en idioma español y encontrar un mensaje en inglés.**

**- Desde el punto de vista del usuario, podría mostrársele un mensaje amigable similar a "Hubo un problema al conectarnos con nuestros servidores. Por favor, inténtalo de nuevo en unos minutos." Y, de ser posible, darle la opción de reintntar enviar el formulario o contactar soporte para que tenga una mejor experiencia.**

-**Fuera de eso, el sistema valida correctamente el ingreso de mails repetidos.**

**Comment by DMFernandez96** [comment]
Hola! Estuve chequeando este bug pero me muestra correctamente el error al querer registrarme con un email ya existente en la base de datos: ![Image](https://github.com/user-attachments/assets/3d4c9835-1f11-466e-8d5d-c6cb901d76e7)

También lo probé en Postman y devuelve un JSON: 
 {
    "statusCode": 409,
    "message": "Email marianabelenluduena@gmail.com already exists"
}
Le consulté a Shei y dice que el error "Error communicating with the main backend" es de Node. Podrían probar devuelta si les sigue apareciendo o se solucionó?

**Comment by marianaluduena** [comment]
Hola! Cómo va? Recién lo probé y ya fue solucionado! Sólo habría que
corregir el mensaje se muestra el inglés y pasarlo a español, pero nada más.

Iba a actualizarlo pero ví que te lo habías asignado y no quise editarlo si
lo estabas viendo.

Más tarde subo el reporte de prueba actualizado con ese detalle.

Saludos!

**Comment by DMFernandez96** [comment]
Ahh genial! Joya, ahora hago ese cambio en el back. Saludos!!

**Comment by marianaluduena** [comment]
Hola! Ya subí el reporte de bug actualizado. Sólo es arreglar el mensaje de error y listo!
