### ISSUE TITLE
Crear endpoint para listar experiencias (GET /experiences)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#15]
Si todavía no se creo nada relacionado a experiencias:
- Creación del Documento ExperienceEntity: Utilizar lombok y definir validaciones.
- Creación de interfaz de ExperienceRepository.
- Creación de gets personalizados que funcionen para las experiencias filtradas.

Luego avanzar con la creación del endpoint requerido:
GET /experiences: recupera una lista de experiencias desde la base de datos, con opciones de filtro por ubicación, tipo y precio.

**Comment by EBDev81** [comment]
**Resumen de la Tarea Abordada Hoy**

**Objetivo:**
Se ha implementado un nuevo endpoint `GET /experiences` en el backend del proyecto **Wander** con el objetivo de recuperar una lista de experiencias desde la base de datos, permitiendo opciones de filtrado por ubicación, tipo y precio máximo.

**Detalles del Trabajo Realizado:**

1. **Modificaciones en `ExperienceService`:**
   - Se añadió el método `getExperiences(String location, String type, Double maxPrice)` a la interfaz `ExperienceService` para definir la funcionalidad de listados de experiencias con filtros opcionales.

2. **Implementación en `ExperienceServiceImpl`:**
   - Se implementó la lógica del método `getExperiences` en la clase `ExperienceServiceImpl`. Este método se encarga de determinar qué filtros están presentes (ubicación, tipo y/o precio) y llamar a los métodos correspondientes del repositorio para recuperar los datos.
   - Se realizó una refactorización del código para simplificar la estructura condicional y mejorar la claridad del método sin necesidad de introducir conceptos adicionales.

3. **Actualización del `ExperienceRepository`:**
   - Se crearon métodos personalizados de consulta, como `findByLocation`, `findByType`, y combinaciones de ellos, para soportar los distintos tipos de filtrado requeridos en la lógica del servicio.

4. **Creación del Endpoint en `ExperienceController`:**
   - Se añadió un nuevo método `getExperiences` en el controlador (`ExperienceController`) que responde a solicitudes `GET /experiences`. Este método permite recibir parámetros opcionales (`location`, `type`, `maxPrice`) para realizar filtrados adecuados y devuelve una lista de experiencias en formato JSON.
   - Se verificó que el endpoint responda correctamente y se manejan posibles errores devolviendo un `HttpStatus.INTERNAL_SERVER_ERROR` si ocurre alguna excepción inesperada.

**Consideraciones Importantes:**
- Se definió que el endpoint `GET /experiences` no requiere un sufijo extra en la URL ya que es la ruta principal para la obtención de todas las experiencias con o sin filtros ya que en la documentación de la API así lo indica.

**Conclusión:**
La tarea de crear el nuevo endpoint `GET /experiences` se completó incluyendo la lógica de negocio y los filtros requeridos. Se encuentra listo para ser integrado con el resto del proyecto.
