### ISSUE TITLE
Crear endpoint para obtener detalles de una experiencia (GET /experiences/:id)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#16]
Si todavía no se creo nada relacionado a experiencias:
- Creación del Documento ExperienceEntity: Utilizar lombok y definir validaciones.
- Creación de interfaz de ExperienceRepository.

Luego avanzar con la creación del endpoint requerido:
GET /experiences/: devuelve los detalles completos de una experiencia, incluyendo descripción, anfitrión, precio y disponibilidad.

**Comment by EBDev81** [comment]
### Creación del Endpoint para Obtener Detalles de una Experiencia por ID

**Resumen del Trabajo Realizado**

En esta iteración, se ha implementado el endpoint para obtener los detalles completos de una experiencia específica, permitiendo a los usuarios acceder a información detallada sobre experiencias turísticas. A continuación, se detalla el trabajo completado.


1. **Actualización del Repositorio (`ExperienceRepository`)**:
   - Se agregó el método `findById(String id)` para permitir la búsqueda de una experiencia en la base de datos por su identificador único (`_id`).

2. **Lógica de Negocio en el Servicio (`ExperienceService` y `ExperienceServiceImpl`)**:
   - Se creó el método `getExperienceById(String id)` en la interfaz `ExperienceService` y su implementación en `ExperienceServiceImpl`.
   - En el método implementado, se incorporó una verificación para lanzar una excepción en caso de que no se encontrara la experiencia con el ID proporcionado, asegurando una respuesta adecuada para los usuarios.

3. **Actualización del Controlador (`ExperienceController`)**:
   - Se creó el endpoint `GET /experiences/{id}` para manejar las solicitudes de detalles completos de una experiencia.
   - El controlador maneja excepciones y devuelve un mensaje claro en caso de que la experiencia solicitada no exista.

**Conclusión**

El nuevo endpoint `GET /experiences/{id}` está implementado en para ser aprobado en la PR.
