### ISSUE TITLE
Crear endpoint para agregar una nueva experiencia (POST /experiences)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#17]
Si todavía no se creo nada relacionado a experiencias:
- Creación del Documento ExperienceEntity: Utilizar lombok y definir validaciones.
- Creación de interfaz de ExperienceRepository.

Luego avanzar con la creación del endpoint requerido:
POST /experiences: crea una nueva experiencia en la base de datos con datos recibidos del BFF, valida al usuario proveedor y retorna una confirmación.

**Comment by EBDev81** [comment]
- Creado el Documento ExperienceEntity.
- Creada la interfaz de ExperienceRepository.
- Creada la ExperienceController para poder gestionar el Endpoint POST /experiences.
- Añadida dependencia javax.validation para poder usar la anotación "NotNull" en ExperienceEntity.
- Falta la lógica que valida que el usuario que intenta crear una experiencia sea un proveedor válido. Como no tenemos la Entity User creada no puedo avanzar en ello. Debemos decidir si se separa user en dos, como provider y user tal y como ha comentado Cris en la pull request: https://github.com/igrowker/i004-wander-back-java/pull/26

**Comment by EBDev81** [comment]
a la espera de la lógica de usuario, intento avanzar con otros temas

**Comment by EBDev81** [comment]
### Resumen del Trabajo Realizado

**Introducción**

He completado la implementación del método `POST` para la creación de experiencias dentro del servicio `ExperienceServiceImpl`, siguiendo las mejores prácticas de seguridad y gestión de datos en el proyecto **Wander**. A continuación, detallo lo que se ha realizado, los puntos clave, y las verificaciones adicionales necesarias.

**Checklist del Trabajo Realizado**

- **Lógica de Negocio en `ExperienceServiceImpl`:**
  - Creada la lógica que se encarga de gestionar la creación de nuevas experiencias turísticas. Esto incluye la validación del usuario y de los datos proporcionados por este.
  - Se asigna automáticamente el `hostId` de la experiencia según el usuario autenticado que realiza la solicitud.

- **Validaciones Exhaustivas:**
  - Se han implementado validaciones detalladas sobre los atributos de la experiencia en el `ExperienceServiceImpl`, asegurando que los campos como `title`, `description`, `location` y `price` cumplan ciertos criterios mínimos antes de ser persistidos.
  - Estas validaciones complementan las anotaciones presentes en la entidad `ExperienceEntity`, como `@NotNull`, para garantizar que los datos estén completos y correctos antes de cualquier operación con la base de datos.

- **Controlador (`ExperienceController`):**
  - Implementado el endpoint `POST /experiences` que interactúa con el servicio para crear una nueva experiencia.
  - El controlador se encarga de manejar las excepciones que se produzcan, proporcionando respuestas HTTP adecuadas (códigos de estado y mensajes claros para los clientes).

**Seguridad**

- Se ha implementado una validación de seguridad adicional en el `ExperienceServiceImpl` para asegurarse de que solo usuarios autenticados con el rol adecuado (`PROVIDER`) puedan crear experiencias.
  - Aunque la pantalla de creación de experiencias sólo es accesible para usuarios proveedores, se realizó esta validación adicional por seguridad, para garantizar un control completo.

**Verificaciones Importantes a Realizar**

- **Protección de Endpoint:**
  - Verificar que en la configuración de seguridad (`SecurityConfiguration`), el endpoint `/experiences` esté correctamente protegido, de manera que solo los usuarios con el rol `PROVIDER` tengan acceso a él.

**Conclusión**

Solo se requiere realizar las verificaciones finales respecto a la seguridad para garantizar que toda la implementación sea óptima.
