### ISSUE TITLE
Crear endpoint para editar una experiencia existente (PUT /experiences/:id)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#18]
Si todavía no se creo nada relacionado a experiencias:

- Creación del Documento ExperienceEntity: Utilizar lombok y definir validaciones.
- Creación de interfaz de ExperienceRepository.

Luego avanzar con la creación del endpoint requerido:
PUT /experiences/: permite a un proveedor editar una experiencia existente. Valida la autorización del usuario y actualiza la información en la base de datos.

Detalles:
- Asegurar que solo los proveedores que crearon la experiencia puedan editarla, implementando validaciones en el endpoint correspondiente.

**Comment by EBDev81** [comment]
### Resumen del Trabajo Realizado: Implementación del Endpoint PUT para Editar Experiencias

Se implementó el endpoint `PUT /experiences/{id}` en el proyecto con el objetivo de permitir a los proveedores editar sus propias experiencias. La implementación asegura que solo los proveedores que hayan creado la experiencia puedan modificarla, garantizando una adecuada lógica de autorización y seguridad.

- **Controlador (`ExperienceController`)**:
  - Se añadió un nuevo endpoint con el método `PUT /experiences/{id}` que permite editar una experiencia existente.

- **Servicio (`ExperienceService` y `ExperienceServiceImpl`)**:
  - Se creó el método `updateExperience(String id, ExperienceEntity newExperienceData)` en `ExperienceService` y se implementó en `ExperienceServiceImpl`.
  - La lógica de negocio realiza la validación para asegurar que solo el proveedor que creó la experiencia pueda editarla.
  - Se asegura que los datos enviados para la actualización se validen antes de persistir los cambios, verificando que cada campo que se actualiza sea válido.

**Validaciones y Seguridad**

- Se validó que el `hostId` de la experiencia coincida con el `id` del usuario autenticado (proveedor), lo cual garantiza que solo el creador de la experiencia pueda modificarla.
