### ISSUE TITLE
Crear endpoint para almacenar una reseña (POST /reviews)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#21]
- Creación del documento ReviewEntity: Utilizar lombok y definir validaciones.
- Creación de interfaz de ReviewRepository.
- Creación de endpoint POST /reviews: almacena una reseña para una experiencia en la base de datos y actualiza el promedio de calificaciones.

Detalles:
-  Implementar la lógica para recalcular el promedio de calificaciones cada vez que una nueva reseña se agregue a una experiencia.

**Comment by EBDev81** [comment]
### Resumen del Trabajo Realizado - POST /reviews

- **Entidad `ReviewEntity`**: Definida con los campos `id`, `experienceId`, `userId`, `rating`, `comment`, y `createdAt`. Se han agregado validaciones con `@NotNull`, `@Min(1)`, y `@Max(5)` para garantizar la integridad de los datos.
- **Repositorio `ReviewRepository`**: Creado para manejar las operaciones con la base de datos de reseñas. Se agregó un método personalizado para buscar reseñas relacionadas con una experiencia por su ID.
- **Servicio `ReviewServiceImpl`**: Lógica para agregar una nueva reseña y recalcular el promedio de calificaciones de la experiencia afectada. Este promedio se actualiza automáticamente cada vez que se agrega una nueva reseña.
- **Controlador**: Se creó el endpoint `POST /reviews` para permitir a los usuarios agregar una reseña para una experiencia, conectándose al servicio para manejar la lógica de negocio.
