### ISSUE TITLE
Configuración Inicial Spring

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i004-wander-back-java#9]
- Configuración de Dependencias
- Estructura MVC (configuration, security, models, repositories, services, controllers)

**Comment by EBDev81** [comment]
Dependencias y mongo hecho. Configurando MVC

**Comment by EBDev81** [comment]
Creación completa de la estructura de carpetas de modelo MVC. He creado dentro de cada carpeta una class o interface dependiendo de las necesidades para poder subir la estructura completa, ya que GIT no sube carpetas vacías. Se pueden cambiar según las necesidades que vayamos teniendo. 
![Image](https://github.com/user-attachments/assets/5f08cc8b-10de-4bd0-b7ec-ea2215b8dcfb)
